# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in valkey-glide.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "pry"

gem "benchmark-ips"
