[package]
name = "valkey"
version = "0.1.0"
edition = "2021"
authors = ["Mohsen Alizadeh <mohsen@alizadeh.us>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
